'use strict';
const el=id=>document.getElementById(id);
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);return n;};
const fmt=v=>v==null?'Unavailable':(v*100).toFixed(2)+'%';
async function api(path,options={}){const response=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json',...(options.method?{Authorization:'Bearer '+el('token').value}:{}),...options.headers}});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function table(headers,rows){const wrap=node('div');wrap.className='table-wrap';const t=node('table'),head=node('thead'),tr=node('tr'),body=node('tbody');headers.forEach(x=>tr.append(node('th',x)));head.append(tr);rows.forEach(values=>{const r=node('tr');values.forEach(v=>{const c=node('td');c.append(v instanceof Node?v:node('span',v));r.append(c);});body.append(r);});t.append(head,body);wrap.append(t);return wrap;}
async function refresh(){el('refresh').disabled=true;try{const [health,network,bench,incidents]=await Promise.all([api('health'),api('network-status'),api('benchmarks'),api('incidents')]);el('health').replaceChildren();Object.entries({'Operating mode':health.mode,'Network capture':network.capture,'Endpoint collector':network.endpoint,'Live scoring':health.ml_mode,'Flow windows this session':network.flows_received,'Queue / drops':`${network.queue_depth} / ${network.queue_drops}`}).forEach(([k,v])=>{const d=node('div');d.append(node('dt',k),node('dd',v));el('health').append(d);});el('healthDetail').textContent=[network.capture_error,network.endpoint_error,health.model_error].filter(Boolean).join(' | ')||'Collectors report their actual state. Benchmark models are separate from live scoring.';el('benchmarks').replaceChildren();for(const r of bench.reports){const a=node('article');a.append(node('h3',r.dataset+' — '+r.model_type),node('p',r.split_policy));a.append(table(['Held-out rows','Precision','Attack recall','False-positive rate','Threshold'],[[r.test.samples.toLocaleString(),fmt(r.test.precision),fmt(r.test.recall),fmt(r.test.fpr),r.threshold.toFixed(4)]]));const detail=node('details');detail.append(node('summary','Attack-family support and limitations'));detail.append(table(['Family','Rows','Flagged','Flag rate'],Object.entries(r.test.families||{}).map(([name,v])=>[name,v.samples,v.flagged,fmt(v.flag_rate)])));(r.limitations||[]).forEach(x=>detail.append(node('p',x)));a.append(detail);el('benchmarks').append(a);}if(!bench.reports.length)el('benchmarks').append(node('p','No completed benchmark reports yet.'));el('incidents').replaceChildren();if(!incidents.incidents.length)el('incidents').append(node('p','No incidents recorded. Start an authorized live session or replay a packet capture.'));else el('incidents').append(table(['Observed','Evidence','Occurrences','Mode','State'],incidents.incidents.map(i=>{const evidence=node('div');evidence.append(node('div',i.reason),node('code',i.last_event_id));const button=node('button','Review event');button.onclick=()=>{el('eventId').value=i.last_event_id;el('labelForm').scrollIntoView({behavior:'smooth'});};evidence.append(node('br'),button);const select=node('select');select.setAttribute('aria-label','State of incident '+i.id);['new','investigating','resolved','false_positive'].forEach(s=>{const o=node('option',s.replaceAll('_',' '));o.value=s;o.selected=s===i.state;select.append(o);});select.onchange=async()=>{try{await api('incidents/'+i.id,{method:'PATCH',body:JSON.stringify({state:select.value,analyst:el('analyst').value})});el('message').textContent='Incident updated.';}catch(e){select.value=i.state;el('message').textContent=e.message;}};return[new Date(i.last_seen*1000).toLocaleString(),evidence,i.count,i.mode,select];})));}catch(e){el('message').textContent='Could not refresh: '+e.message;}finally{el('refresh').disabled=false;}}
el('refresh').onclick=refresh;el('labelForm').onsubmit=async event=>{event.preventDefault();try{await api('labels',{method:'POST',body:JSON.stringify({event_id:el('eventId').value,label:Number(el('labelValue').value),note:el('note').value,analyst:el('analyst').value})});el('message').textContent='Reviewed label saved separately from the prediction.';}catch(e){el('message').textContent=e.message;}};refresh();
async function refreshData(){try{const data=await api('data-progress');el('pipeline').textContent='Pipeline: '+data.pipeline.stage.replaceAll('_',' ');el('downloads').replaceChildren(table(['File','State','Downloaded'],data.downloads.map(d=>[d.path,d.state,(d.bytes/1073741824).toFixed(2)+' / '+(d.size/1073741824).toFixed(2)+' GiB'])));}catch(e){el('pipeline').textContent=e.message;}}
refreshData();setInterval(refreshData,30000);

